In [1]:
import altair as alt
import pandas as pd

In [2]:
%%time
from toolkit import get_mesa_cfs

data3 = get_mesa_cfs()

Collected 428096 records, from 1/2017 up to 1/2020.
CPU times: user 29.7 s, sys: 291 ms, total: 30 s
Wall time: 45.9 s

In [3]:
data3

,Event Number,call_dt,Creation Month,Creation Year,Event Type Code,Event Type Description,Call Priority,Event Address,Street Number,Street Direction,Street Name,Street Type,Latitude,Longitude,Dispatch Group,Division,Response Time Seconds,Response Time Minutes,Location 1
0,P20170010124,2017-01-01 01:24:00,Jan,2017,666,SUICIDE,Emergency,NaN,NaN,NaN,NaN,NaN,NaN,NaN,P2,Central,188,3.13,NaN
1,P20170010661,2017-01-01 19:07:00,Jan,2017,666,SUICIDE,P1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,P4,Superstition,577,9.62,NaN
2,P20170020486,2017-01-02 15:26:00,Jan,2017,261,SEXUAL ASSAULT,P2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,P1,Fiesta,915,15.25,NaN
3,P20170030188,2017-01-03 08:18:00,Jan,2017,310,MOLESTING,P1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,P2,Central,100,1.67,NaN
4,P20170040346,2017-01-04 11:41:00,Jan,2017,666,SUICIDE,P1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,P3,Red Mountain,111,1.85,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
428091,P20200200630,2020-01-20 21:20:25,Jan,2020,487R,THEFT - RESIDENTIAL,P3,300 Block of S RECKER RD MESA,300.0,S,RECKER,RD,33.410529,-111.701665,P4,Superstition,615,10.25,"(33.410529, -111.701665)"
428092,P20200200468,2020-01-20 16:52:33,Jan,2020,238,TRESPASSING,P2,2600 Block of E MCKELLIPS RD MESA,2600.0,E,MCKELLIPS,RD,33.451569,-111.775410,P3,Red Mountain,2780,46.33,"(33.451569, -111.77541)"
428093,P20200200477,2020-01-20 17:01:56,Jan,2020,927W,UNKNOWN TROUBLE - WIRELESS,P1,6800 Block of E URBANA AVE MESA,6800.0,E,URBANA,AVE,33.304174,-111.686260,P4,Superstition,473,7.88,"(33.304174, -111.68626)"
428094,P20200200493,2020-01-20 17:20:58,Jan,2020,921,PROWLER,P1,1200 Block of E 1ST ST MESA,1200.0,E,1ST,ST,33.417228,-111.805001,P3,Red Mountain,254,4.23,"(33.417228, -111.805001)"
428095,P20200200263,2020-01-20 11:38:45,Jan,2020,962,ACCIDENT W/INJURIES,P1,100 Block of N DOBSON RD MESA,100.0,N,DOBSON,RD,33.417148,-111.874161,P2,Central,158,2.63,"(33.417148, -111.874161)"

In [4]:
df3 = data3[data3['Event Type Description'].str.contains('ACCIDENT')].reset_index()
df3 = df3.groupby(['Event Type Description', pd.DatetimeIndex(df3.call_dt).day_name()]).size().reset_index(name='counts')

dows = {'Monday': 1, 'Tuesday': 2, 'Wednesday': 3, 'Thursday': 4, 'Friday': 5, 'Saturday': 6, 'Sunday': 0}

df3['call_dt'] = df3['call_dt'].astype('category').apply(lambda x: dows.get(x))

df3.head(15)

   Event Type Description call_dt  counts
0                ACCIDENT       5    2839
1                ACCIDENT       1    2545
2                ACCIDENT       6    1973
3                ACCIDENT       0    1209
4                ACCIDENT       4    2742
5                ACCIDENT       2    2786
6                ACCIDENT       3    2782
7     ACCIDENT W/INJURIES       5     905
8     ACCIDENT W/INJURIES       1     800
9     ACCIDENT W/INJURIES       6     756
10    ACCIDENT W/INJURIES       0     507
11    ACCIDENT W/INJURIES       4     860
12    ACCIDENT W/INJURIES       2     786
13    ACCIDENT W/INJURIES       3     863
14         FATAL ACCIDENT       4       1

In [5]:
data = df3.rename(columns={'Event Type Description': 'offense', 'call_dt': 'dow', 'counts':'count'})
data

                        offense dow  count
0                      ACCIDENT   5   2839
1                      ACCIDENT   1   2545
2                      ACCIDENT   6   1973
3                      ACCIDENT   0   1209
4                      ACCIDENT   4   2742
5                      ACCIDENT   2   2786
6                      ACCIDENT   3   2782
7           ACCIDENT W/INJURIES   5    905
8           ACCIDENT W/INJURIES   1    800
9           ACCIDENT W/INJURIES   6    756
10          ACCIDENT W/INJURIES   0    507
11          ACCIDENT W/INJURIES   4    860
12          ACCIDENT W/INJURIES   2    786
13          ACCIDENT W/INJURIES   3    863
14               FATAL ACCIDENT   4      1
15         HIT and RUN ACCIDENT   5   1100
16         HIT and RUN ACCIDENT   1    960
17         HIT and RUN ACCIDENT   6    972
18         HIT and RUN ACCIDENT   0    763
19         HIT and RUN ACCIDENT   4    999
20         HIT and RUN ACCIDENT   2    941
21         HIT and RUN ACCIDENT   3    945
22  HIT and RUN ACCIDENT/INJURY   5     72
23  HIT and RUN ACCIDENT/INJURY   1     71
24  HIT and RUN ACCIDENT/INJURY   6     57
25  HIT and RUN ACCIDENT/INJURY   0     45
26  HIT and RUN ACCIDENT/INJURY   4     78
27  HIT and RUN ACCIDENT/INJURY   2     57
28  HIT and RUN ACCIDENT/INJURY   3     87

# Task: Plot frequency of different accident calls each day by day of the week.

In [6]:
alt.Chart(data).mark_bar().encode(
    x='offense',
    y='count',
    color=alt.Color('offense', legend=alt.Legend(orient="left")),
    column='dow'
)

alt.Chart(...)